[global]

dataFrameSerialization = "legacy"

[theme]

base = "light"
primaryColor = "#31347a"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"